
spring:
  sql:
    init:
      mode: never

  web:
    mvc:
      throw-exception-if-no-handler-found: true
      pathmatch:
        matching-strategy: ant_path_matcher

  jackson:
    property-naming-strategy: SNAKE_CASE

# logging.level.org.springframework: DEBUG
