
spring:
  sql:
    init:
      mode: always
      schema-location: file:common/src/main/resources/schema.sql
      data-location: file:common/src/main/resources/data.sql

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:book_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
  password:

third_api:
  rakuten:
    app_id: ${RAKUTEN_API_APP_ID}
