server:
  port: 8080
  servlet:
    session:
      cookie:
        name: SESSION

spring:
  application:
    name: demo

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:book_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:

  jackson:
    property-naming-strategy: SNAKE_CASE
