server:
  port: 8001
  servlet:
      session:
      cookie:
          name: SESSION

spring:
  application:
    name: api

api:
  prefix: /api/v1
  secret: "aosdijfaoijdfo;aisjdo;fiajga"

# logging.level.org.springframework: DEBUG
